# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Devin Ashley Bunch
url: https://devinbunch.github.io
## To build the website locally, comment out the previous line and run
## in terminal: 'bundle ex jekyll serve'. The website will be hosted at
## 'localhost:4000'.

# repository: grantmcdermott/grantmcdermott.github.io
github: [metadata]
email: devinbunch98@gmail.com
description: >- # this means to ignore newlines in the text below
  Devin Bunch's Data Analytics Portfolio hosted on Github.
github_username: devinbunch
minimal_mistakes_skin: "default" #"default" "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /blog/page:num
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Devin Bunch"
  avatar : "/assets/images/profile_pic.png"
  bio    : 
    M.S. Econ 2021, B.S. Mathematics 2020 | University of Oregon
    Data Analyst at Lithia Motors & Driveway.
    Interested in Big data, statistics, and coding
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://devinbunch.github.io"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:devinbunch98@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/devinbunch"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-github"
      url: "https://www.linkedin.com/in/devin-ashley-bunch-9484a4219/"

      
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/devinbunch"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: true
      show_date: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: true

# Social
# https://mmistakes.github.io/minimal-mistakes/docs/configuration/#twitter-cards-and-facebook-open-graph
og_image: /assets/images/default-thumb.png

# Analytics
# https://mmistakes.github.io/minimal-mistakes/docs/configuration/#analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-76482472-1"
    anonymize_ip: false # default

# Comments
# https://mmistakes.github.io/minimal-mistakes/docs/configuration/#disqus
comments:
  provider: "disqus"
  disqus:
    shortname: "devinbunch-blog"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /blog/tag-archive/

exclude: ['*.Rmd'] #this line gets rid of duplicate files in the folders when I knit