# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


# Theme Settings

minimal_mistakes_skin    : "dirt" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title: Devin Ashley Bunch
title_separator          : "|"
subtitle                 : M.S. Economics 2021, B.S. of Mathematics 2020 | University of Oregon
name                     : "Data Analytics Portfolio"
description              :  "Devin Ashley Bunch's website that hosts her Data Analytics Portfolio"
url                      : # the base hostname & protocol for your site e.g. "https://devinbunch.com"

github: [metadata]
email: devinbunch98@gmail.com
search: true


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  
# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  
author:
  name   : "Devin Bunch"
  avatar : "/assets/images/profile_pic.png"
  bio    : 
    Assistant Prof. at the University of Oregon. 
    Interested in environmental economics & data science.
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://devinbunch.com"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:devinbunch98@gmail.com"
    
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/devinbunch"
  
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://www.linkedin.com/in/devin-ashley-bunch-9484a4219/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/devinbunch"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: true
      show_date: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: true

# Social
# https://mmistakes.github.io/minimal-mistakes/docs/configuration/#twitter-cards-and-facebook-open-graph
og_image: /assets/images/default-thumb.png

# Analytics
# https://mmistakes.github.io/minimal-mistakes/docs/configuration/#analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-76482472-1"
    anonymize_ip: false # default


